### ISSUE TITLE
Suggestion (Documentation for CafeTownsend-Angular-Rails)

### ISSUE THREAD

**Issue by sajjadROR** [sectore/CafeTownsend-Angular-Rails#9]
Its can be very helpful for others if you can write steps. how you build your demo application.

**Comment by sectore** [comment]
Have you checked the REAMDE - chapter "[Local Installation](https://github.com/sectore/CafeTownsend-Angular-Rails#local-installation)"?

**Comment by sajjadmurtaza-ror** [comment]
You did a great job.
I want to say for new comer with no AngularJs experience. For those there should be detailed blog from start.
How you send params from templates to controller.
How you did CRUD operation.
like this http://www.sitepoint.com/creating-crud-app-minutes-angulars-resource/

**Comment by sectore** [comment]
Ok, I understand... It is not the goal of this repo to write such a tutorial, just providing code. Anyway, if you think that is a good idea, feel free to write down a blog post. Let's close this issue for now.
